### ISSUE TITLE
Possible compat issue with Better End

### ISSUE THREAD

**Issue by Sunconure11** [ArtixAllMighty/HangMan#11]
https://github.com/quiqueck/BetterEnd/issues/52

You come up several times in an error here.

https://pastebin.com/eqe3rC8Z

https://pastebin.com/3s2edtRz

https://pastebin.com/NCKULuSb

https://pastebin.com/8m8811wf

https://pastebin.com/dHELGFW2

https://gist.github.com/Sunconure11/fe55897fbe7e77d05dce12e5d8c1e14e

https://gist.github.com/Sunconure11/7abf61efa57e81f29264af29506bc074

https://gist.github.com/Sunconure11/58d82e41bddef982195cca3cc12ecdd7

**Comment by AbsolemJackdaw** [comment]
> [20:33:49] [Render thread/WARN]: @Redirect conflict. Skipping hangman.mixins.json:EntitySitOrHangOnNoose->@Redirect::renderEdit(Lnet/minecraft/class_1309;)Z from mod hangman with priority 1000, already redirected by mixins.requiem.client.json:possession.LivingEntityRendererMixin->@Redirect::doesPossessorHaveVehicle(Lnet/minecraft/class_1309;)Z from mod requiem with priority 1000


This is something I can fix. an @ Redirect is not adviced to use in mixins because of compat issues. 
Seems like this one got away under my careful vigilance.
I don't think I can do more about this then that. 
You might want to contact requiem too (i dont know what mod that is) 
if you do so, please link this issue and notify me. 
I found the solution in a library with an annotation processor  that allows for none-intrusive constant edits and it could help the author of requiem too :  
https://github.com/LlamaLad7/MixinExtras/wiki/ModifyExpressionValue

**Comment by Sunconure11** [comment]
@ArtixAllMighty

**Comment by AbsolemJackdaw** [comment]
> @ArtixAllMighty

@Sunconure11 hello there.
got a discord channel ? or do i give you mine ? we may be able to communicate better over there

**Comment by Sunconure11** [comment]
Sunconure11#0616

**Comment by Sunconure11** [comment]
https://github.com/bonsaistudi0s/Creeper-Overhaul/issues/34

This error is of interest too

**Comment by AbsolemJackdaw** [comment]
Quilt's reply : 
> We don't support fabric impl classes because you shouldn't be using them anyway

so the quilt loader isn't compatible with some fabric classes.

The solution here is to not use quilt to load these fabric mods
