### ISSUE TITLE
[Bug]: Entitys not Hanging, stuck in Block & Pig Spawns

### ISSUE THREAD

**Issue by xR4YM0ND** [ArtixAllMighty/HangMan#13]
We got a weird bug on our Fabric 1.19.2 Server
![2022-09-01_13 13 40](https://user-images.githubusercontent.com/97298005/187901133-80cf636e-746f-404d-b699-346df3278998.png)
Every time a Entity or player gets in , a pig spawns and the player/entity is stuck in the block above in a seating postion.

On First time use i right clicked the noose with a pig spawn egg in my hand , and where i stood the pig got created and it wont disappear

Server [latest.log](https://gist.github.com/SpigotDE/46799a60ffe96ceb08664cb4194d8c68)
Client [latest.log](https://gist.github.com/SpigotDE/7efdba472f011ab921fc4bedc6273998)

**Comment by AbsolemJackdaw** [comment]
got optifine ? if yes, remove it and try again

pigs are default entities. if the game can't find an entity, it'll spawn a pig. 
the noose blocks do spawn an entity too, for the entity to ride on and act as if it is hanging. 

optifine messes with entity models and registries. I'm suspecting optifin to be the culprit here

**Comment by xR4YM0ND** [comment]
Nah im not using optifine, you can check client log

Is there a way i can debug this?

**Comment by AbsolemJackdaw** [comment]
are you using anything else then just fabric or forge on your server ? 
anything that isn't the original modloader could have weird side effects.

i dont know what else there is to debug. something is messign with the registries and is not recognizing the noose entity and making a pig out of it. the pig is what minecraft defaults too if there's an ID mismatch, because if i'm not mistaking, the pig id is 0, and it defaults to that if something is wrong. 

try the mod on a clean server with just the mod loader and connect with a clean client with just modloader and left hanging installed

**Comment by xR4YM0ND** [comment]
Alright, i try to disable some render mods and try again

Give me till Monday

**Comment by AbsolemJackdaw** [comment]
fixed in 51b591e2db45d698fe3537b5d9a25aa81364ff3b
